import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'id' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, defaultText?: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Nav
    'nav.brand': 'Badminton Champion League',
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Match',
    'nav.battleLadder': 'Battle',
    'nav.rankLadder': 'Rank',
    'nav.createMatch': '+ Match',
    'nav.ledger': 'Buku Poin',
    'nav.battleHistory': 'Riwayat Battle Points',
    'nav.rankHistory': 'Riwayat Rank Points',
    'nav.notifications': 'Notifikasi',
    'nav.profile': 'Profil Saya',
    'nav.settings': 'Pengaturan Profil',
    'nav.admin': 'Panel Admin',
    'nav.disputes': 'Penyelesaian Sengketa',
    'nav.login': 'Masuk',
    'nav.register': 'Daftar',
    'nav.logout': 'Keluar',

    // Common
    'common.loading': 'Memuat data...',
    'common.save': 'Simpan',
    'common.saved': 'Tersimpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.details': 'Detail Lengkap',
    'common.back': 'Kembali',
    'common.close': 'Tutup',
    'common.status': 'Status',
    'common.actions': 'Tindakan',
    'common.or': 'atau',
    'common.vs': 'VS',
    'common.set': 'Set',
    'common.error': 'Terjadi kesalahan',
    'common.success': 'Berhasil',

    // Match Details & Status
    'match.type.battle': 'Battle Match',
    'match.type.ranked': 'Ranked Match',
    'match.mode.singles': 'Tunggal (1 vs 1)',
    'match.mode.doubles': 'Ganda (2 vs 2)',
    'match.status.ready': 'Siap Main (READY)',
    'match.status.pending_acceptance': 'Menunggu Undangan',
    'match.status.in_progress': 'Sedang Berlangsung',
    'match.status.waiting_approval': 'Menunggu Persetujuan Skor',
    'match.status.disputed': 'Dalam Sengketa (Disputed)',
    'match.status.completed': 'Selesai (Completed)',
    'match.status.cancelled': 'Dibatalkan',
    'match.status.rejected': 'Ditolak',

    // Match Actions & Labels
    'match.venue': 'Lokasi / Lapangan',
    'match.schedule': 'Jadwal Pertandingan',
    'match.description': 'Catatan / Deskripsi',
    'match.liveStream': 'Tonton Live Streaming',
    'match.liveStreamUrl': 'URL Live Streaming (YouTube, TikTok, dll)',
    'match.liveStreamOptional': 'Opsional — masukkan tautan live jika pertandingan disiarkan',
    'match.liveBadge': 'SEDANG LIVE',
    'match.submitScore': 'Input Skor Pertandingan',
    'match.updateScore': 'Perbarui Skor',
    'match.approveScore': 'Setujui Skor',
    'match.disputeScore': 'Ajukan Sengketa / Komplain',
    'match.actionRequired': 'Perlu Tindakan: Harap Tinjau & Setujui Skor',
    'match.alreadyApproved': 'Anda Telah Menyetujui Versi Skor Ini',
    'match.approvalProgress': 'Persetujuan Skor Peserta (Wajib 100% Unanimous)',
    'match.unanimousNote': 'Skor harus disetujui oleh seluruh pemain yang bertanding sebelum poin dialokasikan.',
    'match.acceptInvite': 'Terima Undangan',
    'match.rejectInvite': 'Tolak Undangan',
    'match.inviteAccepted': 'Undangan Telah Diterima',
    'match.pointReward': 'Alokasi Poin Hasil Pertandingan',

    // Create Match Form
    'create.title': 'Buat Pertandingan Baru',
    'create.subtitle': 'Pilih jenis permainan, jadwal, dan undang pemain. Undangan dikirim otomatis.',
    'create.typeLabel': '1. Pilih Tipe Pertandingan',
    'create.modeLabel': '2. Pilih Mode Pertandingan',
    'create.venueSchedule': '3. Lokasi & Waktu Pertandingan',
    'create.selectParticipants': '4. Pilih Pemain',
    'create.partnerLabel': 'Pilih Partner Ganda Anda (Tim A)',
    'create.partnerPlaceholder': 'Pilih partner pemain...',
    'create.opponent1Label': 'Lawan 1 (Tim B)',
    'create.opponent2Label': 'Lawan 2 (Tim B)',
    'create.opponentPlaceholder': 'Pilih lawan pemain...',
    'create.autoConfirmed': 'Otomatis Terkonfirmasi',
    'create.you': 'Anda',
    'create.submitButton': 'Kirim Undangan Pertandingan',
    'create.rankedRequirement': 'Pertandingan Ranked membutuhkan minimal 3 Battle Points untuk setiap pemain.',

    // Profile Settings
    'profile.title': 'Pengaturan Akun & Profil',
    'profile.subtitle': 'Kelola identitas badminton, preferensi permainan, dan media sosial Anda.',
    'profile.photo': 'Foto Profil',
    'profile.photoHint': 'Gunakan foto wajah atau aksi bermain yang jelas. Maks 2MB. Format: JPG, PNG, WebP.',
    'profile.savePhoto': 'Unggah & Simpan Foto',
    'profile.fullName': 'Nama Lengkap',
    'profile.phone': 'Nomor Telepon / WhatsApp',
    'profile.city': 'Kota Asal / Domisili',
    'profile.gender': 'Jenis Kelamin',
    'profile.position': 'Posisi Bermain Favorit',
    'profile.bio': 'Biografi Singkat',
    'profile.visibility': 'Visibilitas Profil',
    'profile.public': 'Publik (Dapat dilihat semua pengguna)',
    'profile.private': 'Privat (Hanya Anda & Admin)',
    'profile.socialMedia': 'Media Sosial (Opsional)',
    'profile.socialHint': 'Tautkan media sosial Anda agar pemain lain dapat terhubung.',
    'profile.instagram': 'Username / Link Instagram',
    'profile.facebook': 'Link Profil Facebook',
    'profile.tiktok': 'Username / Link TikTok',
    'profile.youtube': 'Channel / Link YouTube',
    'profile.saveAll': 'Simpan Perubahan Profil',

    // Public Profile
    'public.dateJoined': 'Bergabung Sejak',
    'public.stats': 'Statistik Pemain',
    'public.totalMatches': 'Total Pertandingan',
    'public.winRate': 'Persentase Menang',
    'public.battlePoints': 'Battle Points (Aktivitas)',
    'public.rankPoints': 'Rank Points (Kompetitif)',
    'public.battleRank': 'Peringkat Battle',
    'public.rankRank': 'Peringkat Ranked',
    'public.streak': 'Winning Streak Saat Ini',
    'public.recentMatches': 'Riwayat Pertandingan Terakhir',
    'public.socialConnect': 'Hubungi Media Sosial',

    // Admin & Disputes
    'admin.disputesTitle': 'Pusat Arbitrase Sengketa Pertandingan',
    'admin.disputesSubtitle': 'Tinjau klaim sengketa peserta, verifikasi set skor, inspeksi riwayat skor sebelumnya, dan eksekusi keputusan mengikat.',
    'admin.activeDisputes': 'Sengketa Aktif',
    'admin.resolvedDisputes': 'Riwayat Keputusan Sengketa',
    'admin.inspectHistory': 'Inspeksi Riwayat Skor',
    'admin.arbitrate': 'Arbitrase Sengketa',
    'admin.filedBy': 'Sengketa Diajukan Oleh',
    'admin.resolutionAction': 'Pilih Tindakan Arbitrase',
    'admin.confirmResult': 'Konfirmasi Skor yang Diajukan',
    'admin.correctScore': 'Koreksi Skor Resmi',
    'admin.cancelMatch': 'Batalkan Match (Refund 3 BP Ranked)',
    'admin.resolutionReason': 'Alasan & Catatan Keputusan (Wajib Diisi)',
    'admin.scoreTimeline': 'Linimasa Riwayat Skor Pemain',
    'admin.version': 'Versi Skor',
    'admin.submittedBy': 'Diinput oleh',
    'admin.decisionNotes': 'Catatan Keputusan Admin',
    'admin.resolvedAt': 'Diselesaikan Pada',

    // Dashboard
    'dashboard.welcome': 'Selamat datang kembali',
    'dashboard.streak': 'Kemenangan Beruntun',
    'dashboard.actionCenter': 'Pusat Tindakan & Persetujuan',
    'dashboard.actionSubtitle': 'Undangan pertandingan dan persetujuan skor yang membutuhkan tindakan Anda.',
    'dashboard.invitations': 'Undangan Pertandingan',
    'dashboard.scoresAwaiting': 'Skor Menunggu Persetujuan Anda',
    'dashboard.upcomingMatches': 'Jadwal Pertandingan Mendatang',
    'dashboard.performanceChart': 'Grafik Tren Performa Poin',
    'dashboard.noUpcoming': 'Belum ada jadwal pertandingan.',
    'dashboard.noRecent': 'Belum ada riwayat pertandingan.',
    'dashboard.entryStake': 'Mata Uang Stake Masuk',
    'dashboard.rankedReady': 'Siap Ranked',
    'dashboard.need3BP': 'Butuh 3 BP',
    'dashboard.season1': 'Musim 1',
    'dashboard.standing': 'Peringkat Battle',
    'dashboard.competitiveRank': 'Peringkat Ranked',
    'dashboard.viewBattleLadder': 'Lihat Battle Ladder →',
    'dashboard.viewRankLadder': 'Lihat Rank Ladder →',
    'dashboard.breakdown': 'Statistik Performa',
    'dashboard.totalMatches': 'Total Pertandingan',
    'dashboard.singlesRecord': 'Rekor Tunggal',
    'dashboard.doublesRecord': 'Rekor Ganda',
    'dashboard.longestStreak': 'Kemenangan Beruntun Terpanjang',

    // Leaderboards
    'leaderboard.battleTitle': 'Papan Peringkat Battle Points',
    'leaderboard.battleSubtitle': 'Peringkat berdasarkan akumulasi Battle Points (+3 Menang, +1 Kalah). Kumpulkan BP untuk membuka pertandingan Ranked.',
    'leaderboard.rankTitle': 'Papan Peringkat Kompetitif Musim 1',
    'leaderboard.rankSubtitle': 'Peringkat kompetitif resmi musim aktif (+3 Menang, -1 Kalah). Memerlukan 3 BP untuk setiap pertandingan.',
    'leaderboard.yourRank': 'Peringkat Anda Saat Ini',
    'leaderboard.searchPlaceholder': 'Cari nama pemain atau username...',
    'leaderboard.allCities': 'Semua Kota / Wilayah',
    'leaderboard.rank': 'Peringkat',
    'leaderboard.player': 'Pemain',
    'leaderboard.matches': 'Pertandingan',
    'leaderboard.record': 'Rekor W/L',
    'leaderboard.winRate': 'Rasio Menang',
    'leaderboard.viewProfile': 'Lihat Profil',

    // Ledger
    'ledger.title': 'Buku Audit Transaksi Poin',
    'ledger.subtitle': 'Log mutasi penambahan dan pengurangan saldo poin dengan audit trail permanen.',
    'ledger.tabBattle': 'Battle Points',
    'ledger.tabRank': 'Rank Points',
    'ledger.tabAll': 'Semua Mutasi',
    'ledger.battleSub': 'Mata uang aktivitas & partisipasi (+3 Win, +1 Loss, -3 Stake Masuk Ranked, +3 Refund Pembatalan)',
    'ledger.rankSub': 'Poin tangga liga kompetitif resmi (+3 Win, -1 Loss, Koreksi Sengketa Admin)',
    'ledger.allSub': 'Log audit gabungan seluruh mutasi saldo poin akun Anda',
    'ledger.currentBalance': 'Saldo Saat Ini',
    'ledger.totalGained': 'Total Poin Masuk',
    'ledger.totalDeducted': 'Total Poin Keluar',
    'ledger.txCode': 'Kode Transaksi',
    'ledger.date': 'Tanggal & Waktu',
    'ledger.category': 'Kategori',
    'ledger.description': 'Deskripsi Mutasi',
    'ledger.previous': 'Saldo Awal',
    'ledger.change': 'Perubahan',
    'ledger.newBalance': 'Saldo Akhir',
    'ledger.match': 'Pertandingan',
    'ledger.noTx': 'Belum ada transaksi poin yang tercatat pada kategori ini.',

    // Landing Page
    'landing.seasonBadge': 'Musim 1: 2026 Badminton Championship Live',
    'landing.heroTitle1': 'TANDING. SKOR.',
    'landing.heroTitle2': 'KUASAI LAPANGAN.',
    'landing.heroSubtitle': 'Platform peringkat pemain & turnamen bulu tangkis paling bergengsi. Kumpulkan Battle Points, tanding di Ranked Matches, dan taklukkan leaderboard resmi dengan verifikasi skor unanimous 100%.',
    'landing.ctaDashboard': 'Buka Dashboard Pemain',
    'landing.ctaRegister': 'Daftar Bergabung di Liga',
    'landing.ctaLeaderboard': 'Lihat Rank Leaderboard',
    'landing.statPlayers': 'Pemain Aktif',
    'landing.statPlayersSub': '500+ Atlet Terverifikasi',
    'landing.statMatches': 'Pertandingan Dimainkan',
    'landing.statMatchesSub': 'Tunggal & Ganda',
    'landing.statApprovals': 'Persetujuan Skor',
    'landing.statApprovalsSub': '100% Verifikasi Unanimous',
    'landing.statLedger': 'Audit Trail Ledger',
    'landing.statLedgerSub': 'Bebas Manipulasi & Permanen',
    'landing.mechanicsBadge': 'Mekanisme Permainan',
    'landing.mechanicsTitle': 'Dua Tangga Liga. Aksi Bulu Tangkis Tanpa Batas.',
    'landing.mechanicsSubtitle': 'Baik untuk pemanasan sparring kasual maupun mengejar kejayaan di puncak klasemen musim ini, sistem poin ganda kami mencatat setiap set pertandingan secara presisi.',
    'landing.battleTitle': 'Battle Matches',
    'landing.battleDesc': 'Pertandingan kasual berfokus pada aktivitas bermain. Sangat cocok untuk sesi rutin malam, sparring persahabatan, dan mengumpulkan Battle Points untuk modal masuk ke pertandingan Ranked.',
    'landing.battleWin': 'Kemenangan Match',
    'landing.battleWinPts': '+3 Battle Points',
    'landing.battleLoss': 'Partisipasi / Kekalahan',
    'landing.battleLossPts': '+1 Battle Point',
    'landing.battleNote': '• Battle Points tidak akan pernah bernilai negatif.',
    'landing.battleCta': 'Lihat Papan Peringkat Battle →',
    'landing.rankedTitle': 'Ranked Matches',
    'landing.rankedDesc': 'Pertandingan kompetitif resmi kejuaraan. Memerlukan stake 3 BP untuk setiap pemain. Raih Rank Points bergengsi, tingkatkan tier musim aktif, dan buktikan diri sebagai pemain nomor 1 liga.',
    'landing.rankedStake': 'Biaya Masuk (Stake)',
    'landing.rankedStakePts': '-3 Battle Points',
    'landing.rankedWin': 'Kemenangan Ranked',
    'landing.rankedWinPts': '+3 Rank Points',
    'landing.rankedLoss': 'Kekalahan Ranked',
    'landing.rankedLossPts': '-1 Rank Point',
    'landing.rankedNote': '• Rank Points dapat bernilai negatif. Direset setiap pergantian musim kompetisi.',
    'landing.rankedCta': 'Lihat Papan Peringkat Rank →',
    'landing.affiliateBadge': 'Program Afiliasi Pemain Resmi',
    'landing.affiliateTitle': 'Ajak Teman & Dapatkan 100 Battle Points Gratis!',
    'landing.affiliateDesc': 'Bagikan link afiliasi Anda ke sesama pemain. Saat teman Anda mendaftar dan menyelesaikan pertandingan pertamanya, Anda dan teman Anda masing-masing langsung menerima 100 Battle Points gratis!',
    'landing.affiliateBenefit1': '+100 BP untuk Anda',
    'landing.affiliateBenefit2': '+100 BP untuk Teman Anda',
    'landing.affiliateBenefit3': 'Otomatis setelah match pertama',
    'landing.affiliateCta': 'Daftar & Dapatkan Link Afiliasi',
    'landing.leadersBadge': 'Juara Teratas',
    'landing.leadersTitle': 'Pemimpin Klasemen Musim Ini',
    'landing.leadersSubtitle': 'Pemain-pemain terbaik yang memimpin lapangan kejuaraan saat ini.',
    'landing.battleTop3': 'Peringkat 3 Besar Battle',
    'landing.rankTop3': 'Peringkat 3 Besar Rank',
    'landing.viewAll': 'Lihat Semua →',
    'landing.winRate': 'Rasio Menang',
    'landing.trustBadge': '100% Terverifikasi & Anti-Kecurangan',
    'landing.trustTitle': 'Persetujuan Skor Mutlak (100% Unanimous) & Audit Ledger',
    'landing.trustDesc': 'Pertandingan tidak dapat membagikan poin melalui klaim sepihak. Setiap peserta (2 pemain di Tunggal, 4 pemain di Ganda) wajib menyetujui versi skor yang sama. Jika ada skor yang direvisi, seluruh persetujuan otomatis direset. Setiap perselisihan langsung menghentikan alokasi poin hingga diputuskan oleh arbiter liga.',
    'landing.trustPillar1': 'Persetujuan Multi-Set Berversi (Multi-version Score Verification)',
    'landing.trustPillar2': 'Kode Transaksi Ledger Permanen per Alokasi Poin',
    'landing.trustPillar3': 'Pusat Arbitrase Sengketa Resmi & Audit Trail Lengkap',

    // Affiliate Feature
    'affiliate.title': 'Program Afiliasi & Referral',
    'affiliate.subtitle': 'Undang teman bermain bulu tangkis dan kumpulkan ratusan Battle Points gratis bersama!',
    'affiliate.howItWorks': 'Cara Kerja Bonus Afiliasi:',
    'affiliate.step1': 'Bagikan link afiliasi unik Anda ke teman atau komunitas bulu tangkis.',
    'affiliate.step2': 'Teman Anda mendaftar melalui link tersebut.',
    'affiliate.step3': 'Setelah teman Anda menyelesaikan 1 pertandingan apapun (Battle atau Ranked), Anda dan teman Anda masing-masing otomatis mendapatkan 100 Battle Points!',
    'affiliate.yourLink': 'Tautan Afiliasi Anda',
    'affiliate.copyLink': 'Salin Link Afiliasi',
    'affiliate.linkCopied': 'Link Berhasil Disalin!',
    'affiliate.totalInvited': 'Total Teman Diundang',
    'affiliate.completed': 'Match Pertama Selesai',
    'affiliate.pending': 'Menunggu Match Pertama',
    'affiliate.totalEarned': 'Total BP Diperoleh',
    'affiliate.referralList': 'Daftar Teman yang Diundang',
    'affiliate.noReferrals': 'Belum ada teman yang mendaftar melalui link afiliasi Anda. Bagikan link sekarang untuk mulai mengumpulkan Battle Points gratis!',
    'affiliate.statusPending': 'Menunggu Match Pertama',
    'affiliate.statusCompleted': 'Selesai (+100 BP Diterima)',
    'affiliate.registerBanner': 'Bonus Undangan Afiliasi: Mendaftar melalui link @{ref}! Anda akan menerima 100 Battle Points setelah menyelesaikan match pertama Anda.',
  },
  en: {
    // Nav
    'nav.brand': 'Badminton Champion League',
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Match',
    'nav.battleLadder': 'Battle',
    'nav.rankLadder': 'Rank',
    'nav.createMatch': '+ Match',
    'nav.ledger': 'Point Ledger',
    'nav.battleHistory': 'Battle Points History',
    'nav.rankHistory': 'Rank Points History',
    'nav.notifications': 'Notifications',
    'nav.profile': 'My Profile',
    'nav.settings': 'Profile Settings',
    'nav.admin': 'Admin Panel',
    'nav.disputes': 'Dispute Resolution',
    'nav.login': 'Sign In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',

    // Common
    'common.loading': 'Loading data...',
    'common.save': 'Save',
    'common.saved': 'Saved',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.details': 'Full Details',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.or': 'or',
    'common.vs': 'VS',
    'common.set': 'Set',
    'common.error': 'An error occurred',
    'common.success': 'Success',

    // Match Details & Status
    'match.type.battle': 'Battle Match',
    'match.type.ranked': 'Ranked Match',
    'match.mode.singles': 'Singles (1 vs 1)',
    'match.mode.doubles': 'Doubles (2 vs 2)',
    'match.status.ready': 'READY',
    'match.status.pending_acceptance': 'Pending Invitations',
    'match.status.in_progress': 'In Progress',
    'match.status.waiting_approval': 'Waiting Score Approvals',
    'match.status.disputed': 'Disputed',
    'match.status.completed': 'Completed',
    'match.status.cancelled': 'Cancelled',
    'match.status.rejected': 'Rejected',

    // Match Actions & Labels
    'match.venue': 'Venue / Court',
    'match.schedule': 'Match Schedule',
    'match.description': 'Description / Notes',
    'match.liveStream': 'Watch Live Stream',
    'match.liveStreamUrl': 'Live Stream URL (YouTube, TikTok, etc.)',
    'match.liveStreamOptional': 'Optional — enter live broadcast stream link',
    'match.liveBadge': 'LIVE STREAM',
    'match.submitScore': 'Submit Match Score',
    'match.updateScore': 'Update Score',
    'match.approveScore': 'Approve Score',
    'match.disputeScore': 'File Dispute',
    'match.actionRequired': 'Action Required: Please Review & Approve Score',
    'match.alreadyApproved': 'You Have Approved This Score Version',
    'match.approvalProgress': 'Participant Approvals (100% Unanimous Required)',
    'match.unanimousNote': 'Score must be unanimously approved by all participating players before points are distributed.',
    'match.acceptInvite': 'Accept Invitation',
    'match.rejectInvite': 'Decline Invitation',
    'match.inviteAccepted': 'Invitation Accepted',
    'match.pointReward': 'Point Allocation Breakdown',

    // Create Match Form
    'create.title': 'Create Badminton Match',
    'create.subtitle': 'Choose game type, mode, schedule, and invite players. Invitations will be sent automatically.',
    'create.typeLabel': '1. Select Match Type',
    'create.modeLabel': '2. Select Match Mode',
    'create.venueSchedule': '3. Venue & Schedule',
    'create.selectParticipants': '4. Select Participants',
    'create.partnerLabel': 'Select Your Doubles Partner (Team A)',
    'create.partnerPlaceholder': 'Choose partner player...',
    'create.opponent1Label': 'Opponent 1 (Team B)',
    'create.opponent2Label': 'Opponent 2 (Team B)',
    'create.opponentPlaceholder': 'Choose opponent player...',
    'create.autoConfirmed': 'Auto Confirmed',
    'create.you': 'You',
    'create.submitButton': 'Send Match Invitations',
    'create.rankedRequirement': 'Ranked matches require at least 3 Battle Points per player upon confirmation.',

    // Profile Settings
    'profile.title': 'Account & Profile Settings',
    'profile.subtitle': 'Manage your badminton identity, playing preferences, and social media links.',
    'profile.photo': 'Profile Photo',
    'profile.photoHint': 'Upload a clear face photo or action shot. Max file size: 2MB. Formats: JPG, PNG, WebP.',
    'profile.savePhoto': 'Upload & Save Photo',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone Number / WhatsApp',
    'profile.city': 'City / Location',
    'profile.gender': 'Gender',
    'profile.position': 'Preferred Playing Position',
    'profile.bio': 'Short Biography',
    'profile.visibility': 'Profile Visibility',
    'profile.public': 'Public (Visible to all users)',
    'profile.private': 'Private (Only you & admins)',
    'profile.socialMedia': 'Social Media (Optional)',
    'profile.socialHint': 'Link your social accounts so other players can connect with you.',
    'profile.instagram': 'Instagram Handle / Link',
    'profile.facebook': 'Facebook Profile Link',
    'profile.tiktok': 'TikTok Handle / Link',
    'profile.youtube': 'YouTube Channel / Link',
    'profile.saveAll': 'Save Profile Changes',

    // Public Profile
    'public.dateJoined': 'Member Since',
    'public.stats': 'Player Statistics',
    'public.totalMatches': 'Total Matches',
    'public.winRate': 'Win Rate',
    'public.battlePoints': 'Battle Points (Activity)',
    'public.rankPoints': 'Rank Points (Competitive)',
    'public.battleRank': 'Battle Ladder Rank',
    'public.rankRank': 'Rank Ladder Rank',
    'public.streak': 'Current Win Streak',
    'public.recentMatches': 'Recent Match History',
    'public.socialConnect': 'Connect on Social Media',

    // Admin & Disputes
    'admin.disputesTitle': 'Match Dispute Arbiter Center',
    'admin.disputesSubtitle': 'Review participant dispute claims, verify sets, inspect score versions, and execute binding resolutions.',
    'admin.activeDisputes': 'Active Disputes',
    'admin.resolvedDisputes': 'Dispute History',
    'admin.inspectHistory': 'Inspect Score History',
    'admin.arbitrate': 'Arbitrate Dispute',
    'admin.filedBy': 'Dispute Filed By',
    'admin.resolutionAction': 'Select Arbiter Action',
    'admin.confirmResult': 'Confirm Submitted Result',
    'admin.correctScore': 'Correct Official Score',
    'admin.cancelMatch': 'Cancel Match (Refund 3 BP Ranked)',
    'admin.resolutionReason': 'Documented Reason (Required)',
    'admin.scoreTimeline': 'Player Score History Timeline',
    'admin.version': 'Score Version',
    'admin.submittedBy': 'Submitted by',
    'admin.decisionNotes': 'Admin Decision Notes',
    'admin.resolvedAt': 'Resolved At',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.streak': 'Match Win Streak',
    'dashboard.actionCenter': 'Pending Action Center',
    'dashboard.actionSubtitle': 'Match invitations and score approvals requiring your immediate action.',
    'dashboard.invitations': 'Match Invitations',
    'dashboard.scoresAwaiting': 'Scores Awaiting Your Approval',
    'dashboard.upcomingMatches': 'Upcoming Scheduled Matches',
    'dashboard.performanceChart': 'Point Performance Trend',
    'dashboard.noUpcoming': 'No upcoming matches scheduled.',
    'dashboard.noRecent': 'No recent matches found.',
    'dashboard.entryStake': 'Entry Stake Currency',
    'dashboard.rankedReady': 'Ranked Ready',
    'dashboard.need3BP': 'Need 3 BP',
    'dashboard.season1': 'Season 1',
    'dashboard.standing': 'Battle Standing',
    'dashboard.competitiveRank': 'Competitive Rank',
    'dashboard.viewBattleLadder': 'View Battle Ladder →',
    'dashboard.viewRankLadder': 'View Rank Ladder →',
    'dashboard.breakdown': 'Performance Breakdown',
    'dashboard.totalMatches': 'Total Matches Played',
    'dashboard.singlesRecord': 'Singles Record',
    'dashboard.doublesRecord': 'Doubles Record',
    'dashboard.longestStreak': 'Longest Win Streak',

    // Leaderboards
    'leaderboard.battleTitle': 'Battle Points Leaderboard',
    'leaderboard.battleSubtitle': 'Ranked by accumulated Battle Points (+3 Win, +1 Loss). Accumulate BP to unlock competitive Ranked matches.',
    'leaderboard.rankTitle': 'Competitive Rank Leaderboard Season 1',
    'leaderboard.rankSubtitle': 'Official active season ladder rankings (+3 Win, -1 Loss). Requires 3 BP entry stake per match.',
    'leaderboard.yourRank': 'Your Current Rank',
    'leaderboard.searchPlaceholder': 'Search by player name or username...',
    'leaderboard.allCities': 'All Cities / Regions',
    'leaderboard.rank': 'Rank',
    'leaderboard.player': 'Player',
    'leaderboard.matches': 'Matches',
    'leaderboard.record': 'Record W/L',
    'leaderboard.winRate': 'Win Rate',
    'leaderboard.viewProfile': 'View Profile',

    // Ledger
    'ledger.title': 'Point Transaction Audit Ledger',
    'ledger.subtitle': 'Immutable point transaction audit log with cryptographically verifiable records.',
    'ledger.tabBattle': 'Battle Points',
    'ledger.tabRank': 'Rank Points',
    'ledger.tabAll': 'All Point Logs',
    'ledger.battleSub': 'Activity & participation currency (+3 Win, +1 Loss, -3 Ranked Entry, +3 Cancel Refund)',
    'ledger.rankSub': 'Official competitive ladder points (+3 Win, -1 Loss, Admin Dispute Corrections)',
    'ledger.allSub': 'Combined audit trail of all point movements in your account',
    'ledger.currentBalance': 'Current Balance',
    'ledger.totalGained': 'Total Inflow',
    'ledger.totalDeducted': 'Total Outflow',
    'ledger.txCode': 'Transaction Code',
    'ledger.date': 'Date & Time',
    'ledger.category': 'Category',
    'ledger.description': 'Description',
    'ledger.previous': 'Previous',
    'ledger.change': 'Change',
    'ledger.newBalance': 'New Balance',
    'ledger.match': 'Match',
    'ledger.noTx': 'No point transactions found for this category.',

    // Landing Page
    'landing.seasonBadge': 'Season 1: 2026 Badminton Championship Live',
    'landing.heroTitle1': 'PLAY. SCORE.',
    'landing.heroTitle2': 'DOMINATE THE COURT.',
    'landing.heroSubtitle': 'The premier competitive badminton player ranking and tournament management platform. Earn Battle Points, compete in Ranked Matches, and conquer the official leaderboards with 100% unanimous score verification.',
    'landing.ctaDashboard': 'Open Player Dashboard',
    'landing.ctaRegister': 'Join the Championship',
    'landing.ctaLeaderboard': 'View Rank Leaderboard',
    'landing.statPlayers': 'Active Players',
    'landing.statPlayersSub': '500+ Verified Athletes',
    'landing.statMatches': 'Matches Played',
    'landing.statMatchesSub': 'Singles & Doubles',
    'landing.statApprovals': 'Score Approvals',
    'landing.statApprovalsSub': '100% Unanimous Verifications',
    'landing.statLedger': 'Audited Ledger',
    'landing.statLedgerSub': 'Zero Fraud & Permanent Integrity',
    'landing.mechanicsBadge': 'Game Mechanics',
    'landing.mechanicsTitle': 'Two Ladders. Unlimited Action.',
    'landing.mechanicsSubtitle': 'Whether warming up in casual sessions or competing for championship glory, our dual-point engine tracks every set with absolute mathematical precision.',
    'landing.battleTitle': 'Battle Matches',
    'landing.battleDesc': 'Casual and participation-focused games. Perfect for weeknight sessions, friendly club sparring, and accumulating Battle Points needed to enter competitive Ranked play.',
    'landing.battleWin': 'Match Victory',
    'landing.battleWinPts': '+3 Battle Points',
    'landing.battleLoss': 'Participation / Loss',
    'landing.battleLossPts': '+1 Battle Point',
    'landing.battleNote': '• Battle Points can never become negative.',
    'landing.battleCta': 'View Battle Leaderboard →',
    'landing.rankedTitle': 'Ranked Matches',
    'landing.rankedDesc': 'Official championship competitive games. Requires a 3 BP entry stake per player. Earn prestigious Rank Points, climb season tiers, and stake your claim as the league #1.',
    'landing.rankedStake': 'Entry Stake',
    'landing.rankedStakePts': '-3 Battle Points',
    'landing.rankedWin': 'Ranked Victory',
    'landing.rankedWinPts': '+3 Rank Points',
    'landing.rankedLoss': 'Ranked Defeat',
    'landing.rankedLossPts': '-1 Rank Point',
    'landing.rankedNote': '• Rank Points can be negative. Resets per competitive season.',
    'landing.rankedCta': 'View Rank Leaderboard →',
    'landing.affiliateBadge': 'Official Player Affiliate Program',
    'landing.affiliateTitle': 'Invite Friends & Earn Free 100 Battle Points!',
    'landing.affiliateDesc': 'Share your unique affiliate link with fellow players. When your invited friend registers and completes their very first match, both you and your friend immediately receive 100 free Battle Points each!',
    'landing.affiliateBenefit1': '+100 BP for You',
    'landing.affiliateBenefit2': '+100 BP for Your Friend',
    'landing.affiliateBenefit3': 'Automatic after first match',
    'landing.affiliateCta': 'Sign Up & Get Affiliate Link',
    'landing.leadersBadge': 'Top Champions',
    'landing.leadersTitle': 'Current Season Leaders',
    'landing.leadersSubtitle': 'Top players dominating the competitive court right now.',
    'landing.battleTop3': 'Battle Ladder Top 3',
    'landing.rankTop3': 'Rank Ladder Top 3',
    'landing.viewAll': 'View All →',
    'landing.winRate': 'Win Rate',
    'landing.trustBadge': '100% Verifiable & Trustless',
    'landing.trustTitle': 'Unanimous Score Approvals & Audited Ledger',
    'landing.trustDesc': 'Matches cannot award points through unilateral creator submissions. Every single participant (2 in Singles, 4 in Doubles) must approve the score version. If any score is updated, all previous approvals reset automatically. Any dispute halts points immediately until review by league arbiters.',
    'landing.trustPillar1': 'Versioned Multi-Set Score Approvals',
    'landing.trustPillar2': 'Immutable Transaction Code per Point Award',
    'landing.trustPillar3': 'Full Dispute Resolution & Audit Trail',

    // Affiliate Feature
    'affiliate.title': 'Affiliate & Referral Program',
    'affiliate.subtitle': 'Invite fellow badminton players and collect hundreds of free Battle Points together!',
    'affiliate.howItWorks': 'How Affiliate Bonuses Work:',
    'affiliate.step1': 'Share your unique affiliate link with friends or your badminton club.',
    'affiliate.step2': 'Your friend registers through your link.',
    'affiliate.step3': 'Once your friend completes 1 match of any kind (Battle or Ranked), both you and your friend automatically get 100 Battle Points!',
    'affiliate.yourLink': 'Your Affiliate Link',
    'affiliate.copyLink': 'Copy Affiliate Link',
    'affiliate.linkCopied': 'Link Copied to Clipboard!',
    'affiliate.totalInvited': 'Total Friends Invited',
    'affiliate.completed': 'First Match Completed',
    'affiliate.pending': 'Awaiting First Match',
    'affiliate.totalEarned': 'Total BP Earned',
    'affiliate.referralList': 'Invited Friends List',
    'affiliate.noReferrals': 'No friends have registered through your link yet. Share your link now to start earning free Battle Points!',
    'affiliate.statusPending': 'Awaiting First Match',
    'affiliate.statusCompleted': 'Completed (+100 BP Awarded)',
    'affiliate.registerBanner': 'Affiliate Invitation Bonus: Registered via @{ref}! You will receive 100 Battle Points after completing your first match.',
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'id',
  setLanguage: () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
})

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('bcl_lang') as Language
    return saved === 'en' ? 'en' : 'id' // Default to 'id' (Indonesian)
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('bcl_lang', lang)
  }

  const t = (key: string, defaultText?: string): string => {
    return translations[language]?.[key] ?? translations.en?.[key] ?? defaultText ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
